services:
  # Movie Manager Web Service
  - type: web
    name: movie_manager
    runtime: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --no-input && echo 'Running migrations...' && python manage.py migrate"
    startCommand: "gunicorn wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
