databases:
  - name: movies_db
    databaseName: movies_db
    user: movies_user

services:
  - type: web
    name: movie_manager
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: movies_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
